import { useAuth } from "@/context/AuthContext"
import { formatUnits } from "viem"
import { gql, request } from "graphql-request"
import { ethers } from "ethers"
import { useNFT } from "@/hooks/useNFT"
import NFTTicketingAbi from "@/contract/ticketnft.json"
