// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ZetaChainTestnet } from "@particle-network/chains";
import { AuthCoreContextProvider } from "@particle-network/auth-core-modal";
import { AuthContext } from "@/context/AuthContext";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// import('buffer').then(({ Buffer }) => {
//   window.Buffer = Buffer;
// });
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} header1_gradient`}>
      <ToastContainer
              position="top-center"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
            />
        <AuthCoreContextProvider
          options={{
            projectId: process.env.NEXT_PUBLIC_APP_PROJECT_ID,
            clientKey: process.env.NEXT_PUBLIC_APP_CLIENT_KEY,
            appId: process.env.NEXT_PUBLIC_APP_APP_ID,
            erc4337: {
              name: "SIMPLE",
              version: "1.0.0",
            },
            wallet: {
              visible: true,
              customStyle: {
                supportChains: [ZetaChainTestnet],
              },
            },
          }}
        >
          <AuthContext>
            {children}
          </AuthContext>
        </AuthCoreContextProvider>
      </body>
    </html>
  );
}
